### ISSUE TITLE
False-positive error highlighting in step functions step usage

### ISSUE THREAD

**Issue by p3et** [theodo/serverless-ide-plugins#10]
I'm using IDEA 2021.1.3 Ultimate on Ubuntu with the Plugin in Version 1.3.1. I got the following highlighting:
![stateMachine](https://user-images.githubusercontent.com/3175942/127278511-bf02de30-f7d7-402f-9955-0c2d232644a5.png)

The state machine works. The following highlighting is imo wrong:
1. _Start:_ shows "Step not used in this file", but it is used at _StartAt: Start_
2. All _Next: *_ and _Default: End_ show "Can't find the Step definition in this file " but the definitions do exist. The other way around, there is no "Step not used in this file" message, so the references are recognized.

**Comment by guillaumem-theodo** [comment]
Thanks for the report. I will have. alook

**Comment by guillaumem-theodo** [comment]
Should be fixed in next version 1.3.3
