### ISSUE TITLE
reported as unsupported for new IntelliJ IDEA version 2021.2

### ISSUE THREAD

**Issue by casualuser** [theodo/serverless-ide-plugins#9]
with new IntelliJ IDEA version 2021.2 release during update this plugin reported as unsupported and will be disabled
please update the plugin

**Comment by casualuser** [comment]
Plugin error: Plugin 'Serverless Framework Completion/Navigation/Syntax' (version '1.3.1') is not compatible with the current version of the IDE, because it requires build 211.* or older but the current build is IU-212.4746.92

**Comment by guillaumem-theodo** [comment]
I will align the version. Thanks for the report

**Comment by guillaumem-theodo** [comment]
Should be ok with new 1.3.3 version
